services:
  postgres:
    image: postgres:16-alpine
    container_name: billetixx-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billetixx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billetixx-app
    restart: always
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/billetixx?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-production-secret-key-here"
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
